version: "3"
services:
  nginx:
    ports:
      - "4000:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    # ports:
    #   - "4000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=kenule
      - MONGO_PASSWORD=kenule500
      - SESSION_SECRET= secret

    command: npm run dev
    # env_file:
    #   - ./.env
  mongoDB:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kenule
      - MONGO_INITDB_ROOT_PASSWORD=kenule500
